In [1]:
import pandas as pd
import numpy as np

In [2]:
match = pd.read_csv('IPL Matches 2008-2020.csv')
delivery = pd.read_csv('IPL Ball-by-Ball 2008-2020.csv')

In [3]:
match.head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

In [4]:
delivery.head()

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
0,335982,1,6,5,RT Ponting,BB McCullum,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
1,335982,1,6,6,BB McCullum,RT Ponting,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
2,335982,1,7,1,BB McCullum,RT Ponting,Z Khan,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
3,335982,1,7,2,BB McCullum,RT Ponting,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
4,335982,1,7,3,RT Ponting,BB McCullum,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore

In [5]:
total_runs_df = delivery.groupby(['id','inning'])['total_runs'].sum().reset_index()

In [6]:
total_runs_df['total_runs'] = total_runs_df['total_runs']+1

In [7]:
total_runs_df = total_runs_df[total_runs_df['inning'] == 1]

In [8]:
match_df = match.merge(total_runs_df[['id','total_runs']],left_on = 'id',right_on = 'id')

In [9]:
match_df['team1'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

Teams with maximum matches

In [10]:
teams = ['Royal Challengers Bangalore',
         'Kings XI Punjab', 
         'Mumbai Indians', 
         'Kolkata Knight Riders',
         'Rajasthan Royals', 
         'Chennai Super Kings',
         'Sunrisers Hyderabad',
          'Delhi Capitals']

In [11]:
match_df['team1'] = match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2'] = match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team1'] = match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2'] = match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

In [12]:
match_df = match_df[match_df['team1'].isin(teams)]
match_df = match_df[match_df['team2'].isin(teams)]

Filerting the matches which are not affected by rain or any other reasons

In [13]:
match_df = match_df[match_df['neutral_venue']==0]

In [14]:
match_df = match_df[['id','city','total_runs','winner']]

In [15]:
delivery_df = match_df.merge(delivery,on= 'id')

In [16]:
delivery_df

,id,city,total_runs_x,winner,inning,over,ball,batsman,non_striker,bowler,...,extra_runs,total_runs_y,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
0,335982,Bangalore,223,Kolkata Knight Riders,1,6,5,RT Ponting,BB McCullum,AA Noffke,...,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
1,335982,Bangalore,223,Kolkata Knight Riders,1,6,6,BB McCullum,RT Ponting,AA Noffke,...,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
2,335982,Bangalore,223,Kolkata Knight Riders,1,7,1,BB McCullum,RT Ponting,Z Khan,...,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
3,335982,Bangalore,223,Kolkata Knight Riders,1,7,2,BB McCullum,RT Ponting,Z Khan,...,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
4,335982,Bangalore,223,Kolkata Knight Riders,1,7,3,RT Ponting,BB McCullum,Z Khan,...,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148111,1237181,Dubai,157,Mumbai Indians,1,12,5,RR Pant,SS Iyer,NM Coulter-Nile,...,0,0,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
148112,1237181,Dubai,157,Mumbai Indians,1,12,6,RR Pant,SS Iyer,NM Coulter-Nile,...,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
148113,1237181,Dubai,157,Mumbai Indians,1,13,1,RR Pant,SS Iyer,KH Pandya,...,1,1,0,0,NaN,NaN,NaN,wides,Delhi Capitals,Mumbai Indians
148114,1237181,Dubai,157,Mumbai Indians,1,13,2,RR Pant,SS Iyer,KH Pandya,...,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
148115,1237181,Dubai,157,Mumbai Indians,1,13,3,SS Iyer,RR Pant,KH Pandya,...,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians

In [17]:
delivery_df = delivery_df[delivery_df['inning']==2]

In [18]:
delivery_df['current_score'] = delivery_df.groupby('id')['total_runs_y'].cumsum()

I:\Users\diwan\AppData\Local\Temp\ipykernel_3588\459334482.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['current_score'] = delivery_df.groupby('id')['total_runs_y'].cumsum()

In [19]:
delivery_df['runs_left'] = delivery_df['total_runs_x']-delivery_df['current_score']

I:\Users\diwan\AppData\Local\Temp\ipykernel_3588\2802540191.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['runs_left'] = delivery_df['total_runs_x']-delivery_df['current_score']

In [20]:
delivery_df['balls_left'] = 120 - (delivery_df['over']*6+delivery_df['ball'])

I:\Users\diwan\AppData\Local\Temp\ipykernel_3588\908924830.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['balls_left'] = 120 - (delivery_df['over']*6+delivery_df['ball'])

In [21]:
delivery_df['player_dismissed']=delivery_df['player_dismissed'].fillna('0')

I:\Users\diwan\AppData\Local\Temp\ipykernel_3588\846986738.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['player_dismissed']=delivery_df['player_dismissed'].fillna('0')

In [22]:
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].apply(lambda x: x if x== '0' else '1').astype(int)

I:\Users\diwan\AppData\Local\Temp\ipykernel_3588\2736754982.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['player_dismissed'] = delivery_df['player_dismissed'].apply(lambda x: x if x== '0' else '1').astype(int)

In [23]:
wickets = delivery_df.groupby('id')['player_dismissed'].cumsum().values

In [24]:
delivery_df['wickets'] = 10 - wickets

I:\Users\diwan\AppData\Local\Temp\ipykernel_3588\548317486.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['wickets'] = 10 - wickets

In [25]:
# current Runrate : runs/overs
delivery_df['current_run_rate'] = delivery_df['current_score']*6/(120 - delivery_df['balls_left'])

I:\Users\diwan\AppData\Local\Temp\ipykernel_3588\699752240.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['current_run_rate'] = delivery_df['current_score']*6/(120 - delivery_df['balls_left'])

In [26]:
# required Runrate = runsleft/overs_left
delivery_df['req_run_rate'] = delivery_df['runs_left']*6/delivery_df['balls_left']

I:\Users\diwan\AppData\Local\Temp\ipykernel_3588\1899778818.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['req_run_rate'] = delivery_df['runs_left']*6/delivery_df['balls_left']

In [27]:
def result(data):
    return 1 if data['batting_team'] == data['winner'] else 0

In [28]:
delivery_df['result'] = delivery_df.apply(result,axis = 1)

I:\Users\diwan\AppData\Local\Temp\ipykernel_3588\3212219128.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['result'] = delivery_df.apply(result,axis = 1)

In [29]:
delivery_df

,id,city,total_runs_x,winner,inning,over,ball,batsman,non_striker,bowler,...,extras_type,batting_team,bowling_team,current_score,runs_left,balls_left,wickets,current_run_rate,req_run_rate,result
121,335982,Bangalore,223,Kolkata Knight Riders,2,6,2,CL White,MV Boucher,AB Agarkar,...,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,0,223,82,10,0.000000,16.317073,0
122,335982,Bangalore,223,Kolkata Knight Riders,2,6,3,CL White,MV Boucher,AB Agarkar,...,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,1,222,81,10,0.153846,16.444444,0
123,335982,Bangalore,223,Kolkata Knight Riders,2,6,4,MV Boucher,CL White,AB Agarkar,...,wides,Royal Challengers Bangalore,Kolkata Knight Riders,2,221,80,10,0.300000,16.575000,0
124,335982,Bangalore,223,Kolkata Knight Riders,2,6,5,MV Boucher,CL White,AB Agarkar,...,wides,Royal Challengers Bangalore,Kolkata Knight Riders,3,220,79,10,0.439024,16.708861,0
125,335982,Bangalore,223,Kolkata Knight Riders,2,6,6,MV Boucher,CL White,AB Agarkar,...,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,3,220,78,10,0.428571,16.923077,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148020,1237181,Dubai,157,Mumbai Indians,2,17,6,HH Pandya,Ishan Kishan,K Rabada,...,NaN,Mumbai Indians,Delhi Capitals,154,3,12,6,8.555556,1.500000,1
148021,1237181,Dubai,157,Mumbai Indians,2,18,1,HH Pandya,Ishan Kishan,A Nortje,...,NaN,Mumbai Indians,Delhi Capitals,155,2,11,6,8.532110,1.090909,1
148022,1237181,Dubai,157,Mumbai Indians,2,18,2,Ishan Kishan,HH Pandya,A Nortje,...,NaN,Mumbai Indians,Delhi Capitals,156,1,10,6,8.509091,0.600000,1
148023,1237181,Dubai,157,Mumbai Indians,2,18,3,HH Pandya,Ishan Kishan,A Nortje,...,NaN,Mumbai Indians,Delhi Capitals,156,1,9,5,8.432432,0.666667,1
148024,1237181,Dubai,157,Mumbai Indians,2,18,4,KH Pandya,Ishan Kishan,A Nortje,...,NaN,Mumbai Indians,Delhi Capitals,157,0,8,5,8.410714,0.000000,1

In [30]:
final_df = delivery_df[['batting_team','bowling_team','city','runs_left','balls_left','wickets','current_run_rate','req_run_rate','result','total_runs_x']]

In [31]:
# Shuffling the dataset
final_df = final_df.sample(final_df.shape[0])

In [32]:
final_df.dropna(inplace = True)

In [33]:
final_df = final_df[final_df['balls_left'] !=0]

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(final_df.drop(columns = ['result']),final_df['result'],test_size = 0.2,random_state = 1)

In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
transformer = ColumnTransformer([('trf',OneHotEncoder(sparse = False,drop = 'first'),['batting_team','bowling_team','city'])],remainder = 'passthrough')

In [36]:
from sklearn.linear_model import LogisticRegression

In [37]:
from sklearn.pipeline import Pipeline
pipe = Pipeline(steps = [('step1',transformer),('step2',LogisticRegression(solver = 'liblinear'))])

In [38]:
pipe.fit(X_train,y_train)

I:\Users\diwan\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [39]:
y_pred = pipe.predict(X_test)

In [40]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [41]:
confusion_matrix(y_test,y_pred)

array([[5413, 1378],
       [1229, 6225]], dtype=int64)

In [42]:
accuracy_score(y_test,y_pred)

0.816988416988417

In [43]:
pipe.predict_proba(X_test)[1]

array([0.80406408, 0.19593592])

In [44]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))